version: '3.8'

services:
  app:
    container_name: budgeting-bill
    build: ./
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:password123@budgeting-bill-psql:5432
      - LOCAL_MODE=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/:/app/app/

    command: gunicorn -b 0.0.0.0:5000 --reload app:my_app

  db:
    container_name: budgeting-bill-psql
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

      # copy the sql script to create tables
      - ./psql/create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql

      # copy the sql script to create views
      - ./psql/create_views.sql:/docker-entrypoint-initdb.d/2_create_views.sql

      # copy the sql script to fill tables with dummy data
      - ./psql/setup_dev_dummy_data.sql:/docker-entrypoint-initdb.d/3_setup_dev_dummy_data.sql
      - ./psql/dev_data.csv:/opt/dev_data.csv

volumes:
  db:
    driver: local
